org: peterfullmer33
app: tweeter
service: tweeter-server
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-aws-documentation
  - serverless-plugin-optimize

functions:
  - ${file(./serverlessFunctions.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
