org: peterfullmer33
app: tweeter
service: tweeter-server
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: false
  excludeDevDependencies: false

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  documentation:
    version: "1"
    title: "Tweeter API"
    description: "This is my tweeter API"
    models: {}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-openapi-documenter
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  - ${file(./serverlessFunctions.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
