org: peterfullmer33
app: tweeter
service: tweeter-server
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  individually: false
  excludeDevDependencies: false

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  - ${file(./serverlessFunctions.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
